### ISSUE TITLE
deactivate accounts after 90 days

### ISSUE THREAD

**Issue by jessicamorris64** [cssat/sprout-issues#196] opened 2022-09-30 23:43 UTC
there is a request to deactivate users (both DCYF and Provider) if they have been inactive for 60 or more days. if they then need to reactivate they can make that request to their Org Admin. this will prevent those who should no longer have access from continuing to have the ability to access Sprout.

alternative if above is not possible:
For DCYF staff...
CSSAT team provides a monthly report of users inactive for 60 days with DCYF emails.

**Comment by subaykan** [comment] 2022-10-05 00:08
Note: we can put a cron in place that executes an update statement like this:

```
update "Users" set state = 'disabled', "disabledAt" = now() where id in (
	select "userId" from "UserSessions" group by "userId" having "userId" in (
		select id from "Users" where state = 'approved'
	) and max("createdAt") < now() - interval '60 days'
);
```

(closed issue #195 as duplicate of this)

**Comment by subaykan** [comment] 2023-05-17 17:42
work is done, need to send out a notification to providers

**Comment by subaykan** [comment] 2023-08-29 19:08
closing out, this was launched to prod

**Closed as completed by subaykan** 2023-08-29 19:08 UTC
Labels: Reviewed Q2 2023
